//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string ShowsToDisplay {
            get {
                return ((string)(this["ShowsToDisplay"]));
            }
            set {
                this["ShowsToDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHidden {
            get {
                return ((bool)(this["ShowHidden"]));
            }
            set {
                this["ShowHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public int ShowsListSeriesNameColumnWidth {
            get {
                return ((int)(this["ShowsListSeriesNameColumnWidth"]));
            }
            set {
                this["ShowsListSeriesNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ShowsListFirstAiredColumnWidth {
            get {
                return ((int)(this["ShowsListFirstAiredColumnWidth"]));
            }
            set {
                this["ShowsListFirstAiredColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ShowsListNetworkColumnWidth {
            get {
                return ((int)(this["ShowsListNetworkColumnWidth"]));
            }
            set {
                this["ShowsListNetworkColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int ShowsListStatusColumnWidth {
            get {
                return ((int)(this["ShowsListStatusColumnWidth"]));
            }
            set {
                this["ShowsListStatusColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ShowsListRatingColumnWidth {
            get {
                return ((int)(this["ShowsListRatingColumnWidth"]));
            }
            set {
                this["ShowsListRatingColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ShowsListRuntimeColumnWidth {
            get {
                return ((int)(this["ShowsListRuntimeColumnWidth"]));
            }
            set {
                this["ShowsListRuntimeColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("151")]
        public int EpisodeListEpisodeNameColumnWidth {
            get {
                return ((int)(this["EpisodeListEpisodeNameColumnWidth"]));
            }
            set {
                this["EpisodeListEpisodeNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int EpisodeListAiredColumnWidth {
            get {
                return ((int)(this["EpisodeListAiredColumnWidth"]));
            }
            set {
                this["EpisodeListAiredColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int EpisodeListEpisodeNumberColumnWidth {
            get {
                return ((int)(this["EpisodeListEpisodeNumberColumnWidth"]));
            }
            set {
                this["EpisodeListEpisodeNumberColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int EpisodeListSeasonColumnWidth {
            get {
                return ((int)(this["EpisodeListSeasonColumnWidth"]));
            }
            set {
                this["EpisodeListSeasonColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int EpisodeListRatingColumnWidth {
            get {
                return ((int)(this["EpisodeListRatingColumnWidth"]));
            }
            set {
                this["EpisodeListRatingColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int EpisodeListEpisodeIdColumnWidth {
            get {
                return ((int)(this["EpisodeListEpisodeIdColumnWidth"]));
            }
            set {
                this["EpisodeListEpisodeIdColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int test {
            get {
                return ((int)(this["test"]));
            }
            set {
                this["test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int test2 {
            get {
                return ((int)(this["test2"]));
            }
            set {
                this["test2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("77")]
        public int test3 {
            get {
                return ((int)(this["test3"]));
            }
            set {
                this["test3"] = value;
            }
        }
    }
}
